### ISSUE TITLE
How to solve this problem

### ISSUE THREAD

**Issue by rodrickcui** [lvyufeng/MindSpore-GAN#1]
![image](https://user-images.githubusercontent.com/104080696/200591515-29e6688c-3d27-4b34-a285-2db05e9a670c.png)

**Comment by lvyufeng** [comment]
please show the MindSpore version, platform(seems Windows?) and Device type(GPU\CPU\Ascend). I have tested on MindSpore1.9 and do not reproduce the problem.

**Comment by rodrickcui** [comment]
MIndSpore version :1.9.0
platform:Linux-x86_64
device type:gpu
It can be run on cpu, but when I try to run it on gpu, it occurs the problem that the picture shows

**Comment by lvyufeng** [comment]
> MIndSpore version :1.9.0 platform:Linux-x86_64 device type:gpu It can be run on cpu, but when I try to run it on gpu, it occurs the problem that the picture shows

I have tried 1.9 on GPU, still can not reproduce the problem.

**Comment by lvyufeng** [comment]
can you create a new environment to test? use instructions below:

```bash
conda create -n mindspore python=3.7
conda activate mindspore
conda install cudatoolkit=11.1 cudnn # or conda install cudatoolkit=10.1 cudnn
pip install mindspore-gpu

```

**Comment by rodrickcui** [comment]
> can you create a new environment to test? use instructions below:
> 
> ```shell
> conda create -n mindspore python=3.7
> conda activate mindspore
> conda install cudatoolkit=11.1 cudnn # or conda install cudatoolkit=10.1 cudnn
> pip install mindspore-gpu
> ```

![image](https://user-images.githubusercontent.com/104080696/200783774-19dd9b76-b71a-4907-9344-79292c42d0b5.png)
If I use conda to install mindspore, it will produce the problem
And I use pip to install, the above picture shows that I have installed successfully. So I am at my wit's end.

**Comment by rodrickcui** [comment]
> can you create a new environment to test? use instructions below:
> 
> ```shell
> conda create -n mindspore python=3.7
> conda activate mindspore
> conda install cudatoolkit=11.1 cudnn # or conda install cudatoolkit=10.1 cudnn
> pip install mindspore-gpu
> ```

Traceback (most recent call last):
  File "acgan.py", line 14, in <module>
    from layers import Dense, Upsample, Embedding, Conv2d, Dropout2d
  File "../layers.py", line 7, in <module>
    from mindspore.ops.operations.image_ops import ResizeBilinearV2, ResizeLinear1D
ImportError: cannot import name 'ResizeBilinearV2' from 'mindspore.ops.operations.image_ops' (/home/ma-user/anaconda3/envs/MindSpore/lib/python3.7/site-packages/mindspore/ops/operations/image_ops.py)
现在又出现这个问题

**Comment by lvyufeng** [comment]
> > can you create a new environment to test? use instructions below:
> > ```shell
> > conda create -n mindspore python=3.7
> > conda activate mindspore
> > conda install cudatoolkit=11.1 cudnn # or conda install cudatoolkit=10.1 cudnn
> > pip install mindspore-gpu
> > ```
> 
> Traceback (most recent call last): File "acgan.py", line 14, in from layers import Dense, Upsample, Embedding, Conv2d, Dropout2d File "../layers.py", line 7, in from mindspore.ops.operations.image_ops import ResizeBilinearV2, ResizeLinear1D ImportError: cannot import name 'ResizeBilinearV2' from 'mindspore.ops.operations.image_ops' (/home/ma-user/anaconda3/envs/MindSpore/lib/python3.7/site-packages/mindspore/ops/operations/image_ops.py) 现在又出现这个问题

是1.9吗，不应该缺这个类才对

**Comment by lvyufeng** [comment]
> > can you create a new environment to test? use instructions below:
> > ```shell
> > conda create -n mindspore python=3.7
> > conda activate mindspore
> > conda install cudatoolkit=11.1 cudnn # or conda install cudatoolkit=10.1 cudnn
> > pip install mindspore-gpu
> > ```
> 
> Traceback (most recent call last): File "acgan.py", line 14, in from layers import Dense, Upsample, Embedding, Conv2d, Dropout2d File "../layers.py", line 7, in from mindspore.ops.operations.image_ops import ResizeBilinearV2, ResizeLinear1D ImportError: cannot import name 'ResizeBilinearV2' from 'mindspore.ops.operations.image_ops' (/home/ma-user/anaconda3/envs/MindSpore/lib/python3.7/site-packages/mindspore/ops/operations/image_ops.py) 现在又出现这个问题

你怎么又从GPU换到modelarts？那上面的Ascend版本应该不是1.8.1以上吧。
